### PR TITLE
feat(HACBS-2279): update kubebuilder-tools to 1.27.1

### PR DESCRIPTION
**Pull request by Troy876**
Updates the kubebuilder-tools in the Makefile from 1.23 to 1.27.1

### CODE REVIEW

**Comment by happybhati** [comment]
For `gitlint` checks commit title should start with a small alphabet [a-z]. It should be `feat(HACBS-2279): update kubebuilder-tools to V1.27.1`

**Review by davidmogar — APPROVED** [review]

**Pull request merged**
