### PR TITLE
refactor: move handler logic to an external library 

### PR DESCRIPTION
**Pull request by davidmogar**
This will allow other operators to define adapters and handlers in a more convenient way.

Signed-off-by: David Moreno García <damoreno@redhat.com>

### CODE REVIEW

**Review by dirgim — APPROVED** [review]
LGTM

**Comment by davidmogar** [comment]
I updated the scope of this PR to move the whole ReconcileHandler to the external library. This should make things easier for other operators but it's a bigger change. Please, take another look.

**Review by johnbieren — COMMENTED** [review]
Code seems good to me.. have you tested the controller out on a cluster with these changes?

**Comment by davidmogar** [comment]
> Code seems good to me.. have you tested the controller out on a cluster with these changes?

I haven’t. Should be the same though.

**Review by theflockers — APPROVED** [review]
Looks good. Noticed the tests were moved but we have no checks yet in the new repo. Are the tests passing for  the new library?

**Comment by davidmogar** [comment]
> Looks good. Noticed the tests were moved but we have no checks yet in the new repo. Are the tests passing for the new library?

Eventually.

**Review by dirgim — APPROVED** [review]
LGTM code-wise

**Review by johnbieren — APPROVED** [review]
I tested this and it works

**Comment by davidmogar** [comment]
Thanks @johnbieren and @theflockers for testing this.

**Pull request merged**
