### PR TITLE
feat(HACBS-542): group pipeline information

### PR DESCRIPTION
**Pull request by davidmogar**
This commit cleans up the ReleaseStrategy by merging related fields like Pipeline, Bundle and Params.

Signed-off-by: David Moreno García <damoreno@redhat.com>

### CODE REVIEW

**Review by johnbieren — CHANGES_REQUESTED** [review]
This breaks the m5 demo files

**Comment by davidmogar** [comment]
I can fix them in a different PR.

**Comment by johnbieren** [comment]
> I can fix them in a different PR.

Why not fix them here so there are no commits in the repo with them broken? :slightly_smiling_face:

**Comment by davidmogar** [comment]
> > I can fix them in a different PR.
> 
> Why not fix them here so there are no commits in the repo with them broken? 🙂

I meant a separate PR to merge both at the same time, but yeah, I can do it in this one.

**Pull request closed without merging**
