### PR TITLE
fix(RHTAPBUGS-714): aggregate clusterroles

### PR DESCRIPTION
**Pull request by ralphbean**
This change should cause these roles to be aggregated into the system wide view, edit, and admin clusterroles.

Notably, it will also cause the roles to be aggregated into the dedicated-admin role, which is what I'm really after.

### CODE REVIEW

**Comment by ralphbean** [comment]
Replaces https://github.com/redhat-appstudio/release-service/pull/237

**Comment by mmalina** [comment]
@ralphbean thanks for the PR. I'll let David (off today) and Johnny review. But in the meantime, can you sign your commit? Here's how to do it in case you haven't done it before: https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

**Review by davidmogar — APPROVED** [review]

**Comment by johnbieren** [comment]
@ralphbean can you rebase this? We have our main branch set to require the commits to be rebased in order to merge

**Comment by johnbieren** [comment]
> @ralphbean thanks for the PR. I'll let David (off today) and Johnny review. But in the meantime, can you sign your commit? Here's how to do it in case you haven't done it before: https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits
> 
> Edit: Now that I've read up on [Aggregated ClusterRoles](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#aggregated-clusterroles) I agree with this change. But I'd still like David to review as well.

@ralphbean still need the commit signed then I can merge

**Pull request merged**
