### PR TITLE
feat(RHTAPREL-806): update operator toolkit reference

### PR DESCRIPTION
**Pull request by happybhati**
This commit updates the `operator-toolkit` refrence
 as result of migration to `konflux-ci` from `redhat-appstudio`
 more details parent EPIC:
 https://issues.redhat.com/browse/RHTAPREL-800

### CODE REVIEW

**Comment by happybhati** [comment]
`Do Not Merge/Hold` preparation PR, Can be merged once repo is migrated to `konflux-ci`!

**Comment by johnbieren** [comment]
Can we open "do not merge" PRs as drafts in the future please?

**Review by johnbieren — APPROVED** [review]
Nice job - can do you the same for the integration service please?

**Review by johnbieren — CHANGES_REQUESTED** [review]
typo in commit title

**Review by johnbieren — APPROVED** [review]

**Pull request merged**
