### PR TITLE
fix(hacbs-1680): bump up go and codecov versions

### PR DESCRIPTION
**Pull request by kasemAlem**
Update go version to 1.18 and codecov-actions to v3

### CODE REVIEW

**Comment by kasemAlem** [comment]
@mmalina @theflockers @scoheb @davidmogar @happybhati

**Comment by mmalina** [comment]
@kasemAlem AFAICS, this PR does not set up codecov to run, but it just updates the versions (to make it work again?). So it's really a fix, right? Can you update the commit message accordingly?

**Comment by kasemAlem** [comment]
@mmalina fixed

**Review by mmalina — APPROVED** [review]
@kasemAlem ok, thanks.

LGTM!

**Comment by davidmogar** [comment]
Commit messages should start with an infinitive. That's it `updating` -> `update`.

**Review by happybhati — DISMISSED** [review]
LGTM👍🏻

**Review by davidmogar — DISMISSED** [review]
Commit title should start with an infinitive (update). I'd propose `fix(hacbs-1680): bump up go and codecov versions` for both the commit and PR titles.

**Review by happybhati — DISMISSED** [review]

**Review by mmalina — APPROVED** [review]

**Pull request merged**
